Repository MCLD/gra4, pull requests merged in 2018-02, with the labels that each got.

#499 Move vendor code to top of profile page
  CHANGELOG.md
  src/GRA.Web/Views/Profile/Index.cshtml
Labels: enhancement

#500 Add first time participation question
  CHANGELOG.md
  src/GRA.Controllers/Base/Controller.cs
  src/GRA.Controllers/JoinController.cs
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Controllers/ViewModel/Join/SinglePageViewModel.cs
  src/GRA.Controllers/ViewModel/Join/Step3ViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/HouseholdAddViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/ParticipantsAddViewModel.cs
  src/GRA.Controllers/ViewModel/Profile/HouseholdAddViewModel.cs
  src/GRA.Data/Model/User.cs
  src/GRA.Domain.Model/User.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/Add.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Participants/HouseholdAdd.cshtml
  src/GRA.Web/Views/Join/Index.cshtml
  src/GRA.Web/Views/Join/Step3.cshtml
  src/GRA.Web/Views/Profile/HouseholdAdd.cshtml
  src/GRA/SiteSettingKey.cs
Labels: enhancement

#502 Add a setting for maximum allowed points
  CHANGELOG.md
  src/GRA.Domain.Service/ActivityService.cs
  src/GRA.Domain.Service/SiteLookupService.cs
  src/GRA/SiteSettingKey.cs
Labels: enhancement

#504 Fix first time field not showing
  src/GRA.Controllers/JoinController.cs
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/ProfileController.cs
Labels: bug

#505 Add daily personal goal
  CHANGELOG.md
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/JoinController.cs
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Controllers/ViewModel/Home/DashboardViewModel.cs
  src/GRA.Controllers/ViewModel/Join/SinglePageViewModel.cs
  src/GRA.Controllers/ViewModel/Join/Step3ViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/HouseholdAddViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/ParticipantsAddViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/ParticipantsDetailViewModel.cs
  src/GRA.Controllers/ViewModel/Profile/HouseholdAddViewModel.cs
  src/GRA.Controllers/ViewModel/Profile/ProfileDetailViewModel.cs
  src/GRA.Data/Model/User.cs
  src/GRA.Data/Repository/UserLogRepository.cs
  src/GRA.Domain.Model/User.cs
  src/GRA.Domain.Repository/IUserLogRepository.cs
  src/GRA.Domain.Service/ActivityService.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/Add.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Participants/Detail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Participants/HouseholdAdd.cshtml
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Join/Index.cshtml
  src/GRA.Web/Views/Join/Step3.cshtml
  src/GRA.Web/Views/Profile/HouseholdAdd.cshtml
  src/GRA.Web/Views/Profile/Index.cshtml
  src/GRA/Defaults.cs
  src/GRA/SiteSettingKey.cs
Labels: enhancement

#506 Improve event entry; fix minor bugs
  src/GRA.Controllers/MissionControl/EventsController.cs
  src/GRA.Controllers/MissionControl/SchoolsController.cs
  src/GRA.Web/Areas/MissionControl/Views/Events/Create.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/Edit.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Participants/Household.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Triggers/Detail.cshtml
  src/GRA.Web/Views/Join/Step1.cshtml
Labels: bug, developer, enhancement

#507 Fix bugs with group handling
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Domain.Service/UserService.cs
Labels: bug

#508 Fix Step3 null model exception
  src/GRA.Controllers/JoinController.cs
Labels: bug, developer

#509 Improve spacing on pre-registration index
  src/GRA.Web/Views/Home/IndexBeforeRegistration.cshtml
Labels: enhancement

#510 Fix OpenGraph meta tags
  CHANGELOG.md
  src/GRA.Controllers/Helpers/SiteTagHelper.cs
Labels: bug, developer
